### ISSUE TITLE
Infinite Loading for combat

### ISSUE THREAD

**Issue by thrandisher** [Morphyum/CompanyMechSalvage#2]
It seems if i take no salvage and go with full money rewards, i end up getting an infinite loading screen on the deploying for combat. If i take atleast 1 salvage part as a reward, combat loads up fast like normal.

I have 1 in my simgameconstant, head set to false, and ive tested with 0 and 1 in the settings.json for recovery chance in mod settings.  Looking at the log there are no errors at all.

**Comment by Morphyum** [comment]
Will look into that later, but can't imagine, that this should be a problem, since i didn't touch anything in the code that would touch the mission creation. But you knows sometimes games call methods at unexpected times.

**Comment by thrandisher** [comment]
Aye, that it does.  The only other mod loader mod i am using is the less pilot injury one. Semi clean install. The only config changes i had done was changing armor steping from 5 to 1, increased mission payout, and made sensor lock last 3 rounds.

 I did a fresh install (Using GOG version) updated to 1.0.2. 3 other mods installed which add equipment.
The only conflict i can think of right now would be the, battletech enhanced star leage edition, which does replace the name of the basic heat sink. The only other mod i could think that would be causing something is JK_Variants which i had added those mechs into the campaign, but i ran into this before i merged them in. There is a small chance i did have his MetadataDatabase.db switched in (I JUST remembered i had  removed his info from the versionmanifest.csv but i might not have switched the db back to original, been a long few days at the ER with family member so i might have sliped and forgot to switch)

I gave up after about 3 mintues of loading for combat, normaly it takes me 20 seconds or so.  I can probably do a full clean install tommorow and try to track down if its a mod conflict if you can reproduce the loading time right away. Who knows, maybe i missed a coma someplace.

**Comment by Morphyum** [comment]
Fresh install, only Modloader and this mod all settings as you said, game loads fine into the mission.

**Comment by thrandisher** [comment]
Ok, ill see it i can track it down tonight since it sounds like a conflict.  Might take me a few days as i might be in and out of the hospital with a family member, and since i take care of her, that takes priority. Im thinking it might be a conflict with BMIT (which adds mechs into campaign) or at least ill start with that and go from there.

**Comment by thrandisher** [comment]
Well this is odd, now i cant reproduce the error...  In the past, I've had BT crash on me while just trying to start it, which does it until i reboot my computer.  I think that is what was happening. One of those mystical unity problems (i have a love/hate/loathe relationship with unity engine).

In my testing tonight i was able to set salvage to 0 with money to full and able to go into combat rather fast, which was getting the infinite loading times before.

Out of that last match i had 5 parts dropped, Rolled: 0.7488799 (in the log) and didn't see anything in inventory go up, but i could be interpreting things wrong.  I've spent half the day in ER with last remaining family member so im a bit scatterbrain right now.

I am going to close this down, and i if i run into the problem again i will try to track down what is causing it before i open up again.
